spring:
  application:
    name: coffee-with-telegram

  #  datasource:
  #    url: jdbc:mysql://localhost:3306/notesdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
  #    username: root
  #    password:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    hikari:
  #      connection-timeout: 20000
  #      minimum-idle: 5
  #      maximum-pool-size: 10
  #      idle-timeout: 300000
  #      max-lifetime: 1200000
  #      auto-commit: true

#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: true

server:
  error:
    include-message: always
  port: 8282

telegram:
  token: 7900292770:AAFCD92cYsWN9xbdtCiICsBbahfePB82uj8
chat_id: 1135897504